[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
launchpad = "7xVm78pUZb9M8SNqtB2nMHFnkJXTL2HXnkQUJFBbv4ZP"

[programs.devnet]
launchpad = "E1PSNCTQhcQYiHihtidJx6ArPrpAoCMM6378mJZquQED"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/chou/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/launchpad.ts"
edge_cases = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/launchpad_edge_cases.ts"
multi_call = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/multi_whitelist.ts"

