[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
lampbit_contracts = "7xVm78pUZb9M8SNqtB2nMHFnkJXTL2HXnkQUJFBbv4ZP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/chou/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
