[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
launchpad = "7xVm78pUZb9M8SNqtB2nMHFnkJXTL2HXnkQUJFBbv4ZP"

[programs.devnet]
launchpad = "EZ5JUytewouCHUDxrvakcjUp5MDuuEMbLEpQHFabgewa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/chou/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/launchpad.ts"
